
export const quotes = [
  { content: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry", book: "The Little Prince" },
  { content: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien", book: "The Lord of the Rings" },
  { content: "Not all those who wander are lost.", author: "J.R.R. Tolkien", book: "The Fellowship of the Ring" },
  { content: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling", book: "Harry Potter and the Sorcerer's Stone" },
  { content: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling", book: "Harry Potter and the Sorcerer's Stone" },
  { content: "There is no friend as loyal as a book.", author: "Ernest Hemingway", book: null },
  { content: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho", book: "The Alchemist" },
  { content: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho", book: "The Alchemist" },
  { content: "Life appears to me too short to be spent in nursing animosity or registering wrongs.", author: "Charlotte Brontë", book: "Jane Eyre" },
  { content: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë", book: "Wuthering Heights" },
  { content: "We are all fools in love.", author: "Jane Austen", book: "Pride and Prejudice" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", book: null },
  { content: "It matters not what someone is born, but what they grow to be.", author: "J.K. Rowling", book: "Harry Potter and the Goblet of Fire" },
  { content: "So we beat on, boats against the current, borne back ceaselessly into the past.", author: "F. Scott Fitzgerald", book: "The Great Gatsby" },
  { content: "The only way to get rid of a temptation is to yield to it.", author: "Oscar Wilde", book: "The Picture of Dorian Gray" },
  { content: "We accept the love we think we deserve.", author: "Stephen Chbosky", book: "The Perks of Being a Wallflower" },
  { content: "It is never too late to be what you might have been.", author: "George Eliot", book: null },
  { content: "To love or have loved, that is enough. Ask nothing further.", author: "Victor Hugo", book: "Les Misérables" },
  { content: "If I loved you less, I might be able to talk about it more.", author: "Jane Austen", book: "Emma" },
  { content: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss", book: "Oh, the Places You'll Go!" },
  { content: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway", book: "A Farewell to Arms" },
  { content: "Perhaps one did not want to be loved so much as to be understood.", author: "George Orwell", book: "1984" },
  { content: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", author: "Jane Austen", book: "Pride and Prejudice" },
  { content: "Who, being loved, is poor?", author: "Oscar Wilde", book: "A Woman of No Importance" },
  { content: "One sees clearly only with the heart. Anything essential is invisible to the eyes.", author: "Antoine de Saint-Exupéry", book: "The Little Prince" },
  { content: "I am no bird; and no net ensnares me: I am a free human being with an independent will.", author: "Charlotte Brontë", book: "Jane Eyre" },
  { content: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide", book: null },
  { content: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou", book: "I Know Why the Caged Bird Sings" },
  { content: "You never really understand a person until you consider things from his point of view.", author: "Harper Lee", book: "To Kill a Mockingbird" },
  { content: "In the end, we’ll all become stories.", author: "Margaret Atwood", book: null },
  { content: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", book: "Hamlet" },
  { content: "All animals are equal, but some animals are more equal than others.", author: "George Orwell", book: "Animal Farm" },
  { content: "To define is to limit.", author: "Oscar Wilde", book: "The Picture of Dorian Gray" },
  { content: "When you play the game of thrones, you win or you die.", author: "George R.R. Martin", book: "A Game of Thrones" },
  { content: "Not all those who wander are lost.", author: "J.R.R. Tolkien", book: "The Fellowship of the Ring" },
  { content: "The answer to the ultimate question of life, the universe, and everything is 42.", author: "Douglas Adams", book: "The Hitchhiker's Guide to the Galaxy" },
  { content: "Brave doesn’t mean you’re not scared. It means you go on even though you’re scared.", author: "Angie Thomas", book: "The Hate U Give" },
  { content: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling", book: "Harry Potter and the Chamber of Secrets" },
  { content: "Fear doesn’t shut you down; it wakes you up.", author: "Veronica Roth", book: "Divergent" },
  { content: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "J.K. Rowling", book: "Harry Potter and the Prisoner of Azkaban" },
  { content: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin", book: "Phrynette Married" },
  { content: "Some infinities are bigger than other infinities.", author: "John Green", book: "The Fault in Our Stars" },
  { content: "The greatest adventures lie in the challenges we undertake.", author: "Paulo Coelho", book: "The Alchemist" },
  { content: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", book: null },
  { content: "Atticus, he was real nice. Most people are, Scout, when you finally see them.", author: "Harper Lee", book: "To Kill a Mockingbird" },
  { content: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings", book: null },
  { content: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", book: "All’s Well That Ends Well" },
  { content: "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.", author: "Madeleine L'Engle", book: null },
  { content: "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be.", author: "Stephen Chbosky", book: "The Perks of Being a Wallflower" }
];


 
